apiVersion: v1
kind: Pod
metadata:
  name: pvs
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true    
  - name: pvs
    image: gcr.io/pvs-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: pvs-secret
        mountPath: /pvs/.docker
  volumes:
    - name: pvs-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json